### ISSUE TITLE
Erreur 500 à l'obtention du rapport

### ISSUE THREAD

**Issue by Vrock691** [VLD-dev-team/Social-Co2#16]
ENDPOINT : GET /rapport

Réponse du serveur sur postman : 
```
{
    "error": true,
    "error_message": "Internal Server Error",
    "error_code": 2
}
```

Erreur node : 
```
Error retrieving notifications: ReferenceError: userID is not defined
    at /home/vldsite/Social-Co2/server/apiroutes/rapport.js:17:78
    at Layer.handle [as handle_request] (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:280:10)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:136:14)
    at /home/vldsite/Social-Co2/server/utils/requireAuth.js:37:7
```

**Comment by Kez0X** [comment]
rapport fonctionne correction dans le dernier commit : pull request #14
