### ISSUE TITLE
Impossible de liker un post

### ISSUE THREAD

**Issue by Vrock691** [VLD-dev-team/Social-Co2#19]
ENDPOINT : POST /social/like

Erreur node : 
```
Error: Unknown column 'userName' in 'field list'
    at Packet.asError (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'userName' in 'field list'",
  sql: "SELECT userName FROM users WHERE userID = 'e90oW5bPEXQQak49uuXosoi4dxE2' ;"
}
```

**Comment by Kez0X** [comment]
Issue fix : Problème de requête
