### ISSUE TITLE
Impossible d'obtenir les commentaires d'un post

### ISSUE THREAD

**Issue by Vrock691** [VLD-dev-team/Social-Co2#20]
ENDPOINT : GET /social/comments

Erreur node : 
```
ReferenceError: userID is not defined
    at /home/vldsite/Social-Co2/server/apiroutes/social.js:183:53
    at Layer.handle [as handle_request] (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:280:10)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:136:14)
    at /home/vldsite/Social-Co2/server/utils/requireAuth.js:37:7
```

**Comment by Kez0X** [comment]
fix issue : oublie de définition de constante
