### ISSUE TITLE
Erreur lors du post d'un commentaite

### ISSUE THREAD

**Issue by Vrock691** [VLD-dev-team/Social-Co2#21]
ENDPOINT: POST /social/comments

Erreur node : 
```
Error: Unknown column 'userName' in 'field list'
    at Packet.asError (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/vldsite/Social-Co2/server/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'userName' in 'field list'",
  sql: "SELECT userName FROM users WHERE userID = 'e90oW5bPEXQQak49uuXosoi4dxE2' ;"
}
```

**Comment by Kez0X** [comment]
Issue régler mais problème de push, permission denied

**Comment by Kez0X** [comment]
[kez0x@fedora-luka server]$ git push
Énumération des objets: 9, fait.
Décompte des objets: 100% (9/9), fait.
Compression par delta en utilisant jusqu'à 4 fils d'exécution
Compression des objets: 100% (5/5), fait.
Écriture des objets: 100% (5/5), 540 octets | 135.00 Kio/s, fait.
Total 5 (delta 4), réutilisés 0 (delta 0), réutilisés du paquet 0 (depuis 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/Vrock691/Social-Co2.git
 ! [remote rejected] server-branch -> server-branch (permission denied)
erreur : impossible de pousser des références vers 'https://github.com/Vrock691/Social-Co2.git'
