### ISSUE TITLE
Erreur lors de l'envoi d'un post avec une activitée liée

### ISSUE THREAD

**Issue by Vrock691** [VLD-dev-team/Social-Co2#30]
ENDPOINT : POST /social/post

```
TypeError: NaN is not a function
    at /home/vldsite/Social-Co2/server/apiroutes/social.js:376:36
    at Layer.handle [as handle_request] (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/index.js:280:10)
    at next (/home/vldsite/Social-Co2/server/node_modules/express/lib/router/route.js:141:14)
    at /home/vldsite/Social-Co2/server/utils/requireAuth.js:37:7
```

**Comment by Kez0X** [comment]
Erreur résolu : vient du GET

**Comment by Kez0X** [comment]
Erreur résolu : isNan not Nan
