### ISSUE TITLE
Date type social/feed

### ISSUE THREAD

**Issue by Kez0X** [VLD-dev-team/Social-Co2#54]
L'erreur : 

/home/vldsite/Social-Co2/server/apiroutes/social.js:83
                const isoDateString = date.toISOString();
                                           ^

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at /home/vldsite/Social-Co2/server/apiroutes/social.js:83:44
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 17)
    at async /home/vldsite/Social-Co2/server/apiroutes/social.js:43:22

Node.js v18.19.0

Les 3 lignes concernées : 

const date = new Date(postLinkedActivity["activityTimestamp"]);
const isoDateString = date.toISOString();
postLinkedActivity["activityTimestamp"] = isoDateString

Fonctionne avec postman mais pas avec le serveur...
Sous forme de commentaire pour le moment.

Problème ne venant pas du serveur après test peut être du Client. Vérification requise.

**Comment by Kez0X** [comment]
![Capture d’écran du 2024-04-27 15-47-02](https://github.com/VLD-dev-team/Social-Co2/assets/118253031/36ca6822-3371-485e-9360-64fcaf8d6faa)
